### ISSUE TITLE
Inline cubit mesh does not work in parallel

### ISSUE THREAD

**Issue by tjfulle** [SNLComputation/lgrtk#23]
@ibaned for the input file (say, `input.yaml`)

```yaml
...
mesh:
  CUBIT:
     commands: |
      ...
      export genesis "mesh.exo"
    Exodus file: mesh.exo
```

Running as

```
mpiexec -np <N> lgr input.yaml
```

results in runtime failure (some processes can't find the exodus file).  Perhaps I am missing a `nem_spread` command?
